### ISSUE TITLE
Need changes to Gnut distribution and issuance

### ISSUE THREAD

**Issue by jaekwon** [gnuclear/atom-whitepaper#22]
There are three problems that I see, and possible changes:

1. The Bitcoin issuance is slightly flawed, in that the Bitcoins given to the GnuClear foundation can be recycled to get more Gnuts, thus centralizing the ownership to the GnuClear foundation.  This can be mitigated with transparency showing where the money is being spent.  If the bitcoins are clearly misused, the gnut holders can vote to change the foundation address.

2. There isn't enough funding in the genesis for the foundation.  I mean, can get by only on salary for two or three people, but it would help to make additional hires as well, and to do that we need a bit of capital infusion.

3. There ought to be a pool for bounties, so non-foundation individuals and entities can help with various work loads.

For points 2 and 3 I suggest we have a bit of premine for the foundation, with the expectation of transparency, say of 15% of the total allocated gnuts on genesis day, to get diluted further by bitcoin issuance, where 2/3 goes to early funding of the foundation, and 1/3 goes to bounties over time.  What do you think?

**Comment by zmanian** [comment]
I think 1 is manageable and doesn't need any special functionality.

Individuals who are willing to publicly idenitify themselves should be able to buy gnuts at a discount beford the network launch.to resolve 2

**Comment by jaekwon** [comment]
It's hard to compute what the "discount" would be, but we could just set a price and sell them (rather than have any auction mechanics) which could help lock in a (probably) discounted price.

I will update genesis issuance with 10% premine to be sold to qualified investors, and 5% to be allocated for bounties for early development, all of which will be transparent.

BTW, we the foundation also need strong incentives to develop this system to completion, not because we wouldn't otherwise, but because without it, the system loses credibility.  I think, even accounting for bitcoin issuance donations and subsidies via the tax mechanism, having less than 10% ownership of the network makes for a less credible system, whether or not it's plenty for us.

For this, I think we may have an additional 10% to be vested over say 6 years, which can be stopped at any time by governance (e.g. +1/2 votes).  Then, the network can vote in another foundation and perhaps consider another 10% inflation, if need be when the time comes.

This makes the total potential premine ownership of the foundation equal to 10% + the ~$1M in funding + any bitcoin donations over time.  The 10% does allow us to expend all of the funding toward development with no reservation for e.g. founder ownership.

Thoughts?

**Comment by ebuchman** [comment]
I think a vesting foundation is a great model.

So in summary we'd have something like:
- 13.4M vesting to the initial 67 validators (200,000 vesting gnuts each).
- 10% of that (1.34M) is sold off to qualified investors to raise some initial capital for the foundation to get the dev work done (say, ~$1M).
- Another 1.34M vests over 6 years for the foundation to pay for long term maintenance and development.
- Half of that (0.67M) is allocated for development bounties. 
- Finally, 6.7M would be auctioned off via bitcoin, at 21,474 per week. 

So the expected number of gnuts after 6 years, including all vesting and auctions, would be 23.45M

**Comment by jaekwon** [comment]
Changed the number of validators to 50, so it's:

* 10M to genesis validators
* 1.2M vesting to foundation over 4 years
* 1.2M to supporters (they aren't investors, they're expected to work with us).
* 1.0M to bounties.
* just under 6.7M issued through ether (not bitcoin) over 6 years.

Grand total of just under 20.1M gnuts.

**Comment by zmanian** [comment]
/jk So then we call the ASIC company we are starting 20.1?

**Comment by ebuchman** [comment]
cool. and why'd you change to ether over bitcoin?

**Comment by ebuchman** [comment]
test

**Comment by jaekwon** [comment]
So we can write a contract that requires burners/donators to sign a statement.

**Comment by ebuchman** [comment]
well, we can still do that in bitcoin. but obviously cleaner in eth

**Comment by jaekwon** [comment]
Changes proposed in #30

**Comment by LeeBlues** [comment]
JaeKwon, When is pre-sale? thanks.

**Comment by jaekwon** [comment]
@LeeBlues , October.

**Comment by jaekwon** [comment]
https://github.com/gnuclear/atom-whitepaper/blob/master/PLAN.md
